name: Python Package using Conda

on: [pull_request]

jobs:
  code_quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      if: always()
      run: |
        pip install -r requirements.txt

    - name: Lint with Pylint
      if: always()
      run: |
        pylint $(git ls-files *.py)

    - name: Lint with Mypy
      if: always()
      run: |
        mypy $(git ls-files *.py)

    - name: Lint with Pydocstyle
      if: always()
      run: |
        pydocstyle --convention=numpy $(git ls-files *.py)
