# Workflow to run CAM-ML test suite
name: TestSuiteUbuntu

# Controls when the workflow will run
on:
  # Triggers the workflow on pushes to the "main" branch, i.e., PR merges
  push:
    branches: [ "main" ]

  # Triggers the workflow on pushes to open pull requests with code changes
  pull_request:
    paths:
      - '.github/workflows/test_suite_ubuntu.yml'
      - '**.f90'
      - '**.F90'
      - '**CMakeLists.txt'
      - '**requirements.txt'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Cancel jobs running if new commits are pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# Workflow run - one or more jobs that can run sequentially or in parallel  
jobs:
  # This workflow contains a single job called "test-suite-ubuntu"
  test-suite-ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    # These steps represent sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        with:
          persist-credentials: false
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # MPI is required by pFUnit
      - name: Install an MPI distribution
        run: |
          sudo apt update
          sudo apt install mpich

      - name: Install pFUnit
        run: |
          export FC=/usr/bin/gfortran
          export MPIF90=/usr/bin/mpif90
          git clone -b v4.10.0 https://github.com/Goddard-Fortran-Ecosystem/pFUnit.git
          mkdir pFUnit/build
          cd pFUnit/build
          cmake ..
          make -j 4 install    